[package]
name = "horizcoin-node"
description = "HorizCoin blockchain node executable"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]