[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/ds-test/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default.optimizer]
enabled = true
runs = 200

[profile.default.model_checker]
contracts = {
    "/src/governance/HorizGovernor.sol" = ["HorizGovernor"],
    "/src/treasury/HorizTreasury.sol" = ["HorizTreasury"],
    "/src/token/HorizCoinToken.sol" = ["HorizCoinToken"]
}

[profile.ci]
fuzz = { runs = 1000 }
invariant = { runs = 100, depth = 100 }

[profile.lite]
optimizer = false
via_ir = false

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }