[package]
name = "horizcoin-codec"
description = "Serialization codec for HorizCoin"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]

[lints]
workspace = true