name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install RocksDB dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          clang \
          pkg-config \
          libsnappy-dev \
          zlib1g-dev \
          libbz2-dev \
          libzstd-dev \
          liblz4-dev

    - name: Install Rust 1.70.0
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.70.0
        components: rustfmt, clippy

    - name: Set up Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Build workspace
      run: cargo build --workspace

    - name: Run tests
      run: cargo test --all --verbose

    - name: Test binaries
      run: |
        cargo run -p horizcoin-node
        cargo run -p horiz-cli -- --help

    - name: Verify metadata
      run: cargo metadata --format-version 1 --no-deps > /dev/null