name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          clang \
          pkg-config \
          libsnappy-dev \
          zlib1g-dev \
          libbz2-dev \
          libzstd-dev \
          liblz4-dev
    
    - name: Install Rust 1.70.0
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.70.0
    
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
    
    - name: Check formatting
      run: cargo fmt --all -- --check
    
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings -A clippy::cargo-common-metadata
    
    - name: Build workspace
      run: cargo build --workspace --locked
    
    - name: Run tests
      run: cargo test --all --locked --verbose
    
    - name: Test node binary
      run: cargo run -p horizcoin-node
    
    - name: Test CLI binary
      run: cargo run -p horiz-cli -- --help