name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.70.0

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install RocksDB dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake clang pkg-config libsnappy-dev zlib1g-dev libbz2-dev libzstd-dev liblz4-dev
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.RUST_VERSION }}
        components: rustfmt, clippy
    
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
    
    - name: Check formatting
      run: cargo fmt --all --check
    
    - name: Run Clippy
      run: cargo clippy --all-targets -- -D warnings
    
    - name: Build workspace
      run: cargo build --workspace --locked
    
    - name: Run tests
      run: cargo test --all --locked --verbose
    
    - name: Test binary execution
      run: |
        cargo run -p horizcoin-node
        cargo run -p horiz-cli -- --help