name: Deploy Web Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  # Build and test before deployment
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install RocksDB dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake clang pkg-config libsnappy-dev zlib1g-dev libbz2-dev libzstd-dev liblz4-dev
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.70.0
        components: rustfmt, clippy
    
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
    
    - name: Build workspace
      run: cargo build --workspace
    
    - name: Test horizcoin-web binary
      run: |
        # Start web server in background
        cargo run -p horizcoin-web &
        WEB_PID=$!
        
        # Wait for server to start
        sleep 5
        
        # Test endpoints
        curl -f http://localhost:3000/healthz
        curl -f http://localhost:3000/ | grep -q "HorizCoin"
        
        # Clean up
        kill $WEB_PID

  # Deploy to Railway (if configured)
  deploy-railway:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ secrets.RAILWAY_TOKEN != '' }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Railway CLI
      run: npm install -g @railway/cli
    
    - name: Deploy to Railway
      run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID || 'horizcoin-web' }}
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  # Deploy to Render (if using render.yaml)
  deploy-render:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Trigger Render Deploy
      run: |
        echo "Render deployment will be triggered automatically via GitHub integration"
        echo "The render.yaml file configures the deployment settings"